### ISSUE TITLE
DLI Not working?

### ISSUE THREAD

**Issue by DevRanger** [KFDtool/KFDtool#56]
I've tried 3 installs on 3 different devices, none of them are working. DLI was working on an older build (for me at least) and after updating to latest, it stopped working.

Device: APX 900 (SW AES Enabled on flash)
KFDTool Ver: Latest (as of submission of this issue)
Issue: See image
![image](https://user-images.githubusercontent.com/30966416/193321587-cde37bde-8e6f-4fd8-81ac-f6b09b977ffa.png)

Windows detects the radio, pops up the network thing that it does when you connect an APX and CPS works fine so I know its not my cable or my system?

**Comment by duggerd** [comment]
What is the APX 900 FW version?

Also confirm these settings in CPS:

![image](https://user-images.githubusercontent.com/33073599/193326140-889e23ee-0166-4bf3-9c64-5a57294eca5b.png)

**Comment by duggerd** [comment]
As well as:

![image](https://user-images.githubusercontent.com/33073599/193328520-050b161c-5696-45cc-aa13-0e7b06a688a8.png)

**Comment by duggerd** [comment]
I tested a radio running R27.00.01 and it worked using the current KFDtool release 1.5.0 on Windows 10 x64.

Can you ping the radio at 192.168.128.1? That error message you are getting appears when the radio is not responding at all.

Also one more setting to check:

![image](https://user-images.githubusercontent.com/33073599/193350955-b11d4241-f11e-4790-872b-24fb7f16ca8e.png)

**Comment by DevRanger** [comment]
When I attempt to ping 192.168.128.1 (the radio's IP) it times out. Tested across my 3 devices and 2 separate prog cables.

Systems are on win 10 x64 build 21H2

The systems see the APX connected, popup the normal network thing that windows does (then I click "allow") and I see the radio network in task manager. CPS & tuner work fine, KFDTool just isint seeing it.

I've been trying to figure out why its not working for the past few weeks but at this point I feel like I've eliminated the computers and my prog cables being the issue...

![image](https://user-images.githubusercontent.com/30966416/193352106-54200e39-0ca6-4e2b-b3dd-543c9f6000d7.png)
![image](https://user-images.githubusercontent.com/30966416/193352137-9973fb4e-7f1c-4452-bc51-36c7e7af2bd0.png)

**Comment by duggerd** [comment]
If you can't ping the radio, that would be the larger problem. For some reason your machines are acting differently than a typical install.

Is there any firewall or antivirus software installed on these machines?

Does ipconfig /all show this for the radio?

![image](https://user-images.githubusercontent.com/33073599/193354366-63a4af13-c0de-4369-a7a7-442f4898ebda.png)

**Comment by duggerd** [comment]
Yikes...something is up with that radio.

It explains the CPS/Tuner working but not KFDtool. CPS/Tuner dynamically queries Windows to discover the IP address of the radio. KFDtool uses a default of 192.168.128.1. I bet if you go in KFDtool, Device -> Edit, and change 192.168.128.1 to 208.27.88.51, it will work.

**Comment by DevRanger** [comment]
right as you were responding, i tried that and it worked lol. thank you for the help!!!
